local item_sounds = require("__base__.prototypes.item_sounds")
local structures_subgroup = "programmable-structures"
data:extend{
    {
        type = "selection-tool",
        name = "unit-remote-control",
        icon = "__aai-programmable-vehicles__/graphics/icons/unit-remote-control.png",
        icon_size = 64,
        flags = {"not-stackable", "only-in-cursor", "spawnable"},
        subgroup = "spawnables",
        order = "c[automated-construction]-e[unit-remote-control]",
        stack_size = 1,
        select = {
            border_color = {r = 0.3, g = 0.9, b = 0.3},
            mode = {"same-force"},
            cursor_box_type = "copy",
        },
        alt_select = {
            border_color = {r = 0.9, g = 0.9, b = 0.3},
            mode = {"same-force"},
            cursor_box_type = "entity",
        },
        pick_sound = item_sounds.combinator_inventory_pickup,
        drop_sound = item_sounds.combinator_inventory_move,
        inventory_move_sound = item_sounds.combinator_inventory_move,
    },
    {
        type = "selection-tool",
        name = "path-remote-control",
        icon = "__aai-programmable-vehicles__/graphics/icons/path-remote-control.png",
        icon_size = 64,
        flags = {"not-stackable", "only-in-cursor", "spawnable"},
        subgroup = "spawnables",
        order = "c[automated-construction]-e[path-remote-control]",
        stack_size = 1,
        select = {
            border_color = {r = 0.3, g = 0.9, b = 0.3},
            mode = {"same-force"},
            cursor_box_type = "copy",
        },
        alt_select = {
            border_color = {r = 0.3, g = 0.3, b = 0.9},
            mode = {"same-force"},
            cursor_box_type = "entity",
        },
        pick_sound = item_sounds.combinator_inventory_pickup,
        drop_sound = item_sounds.combinator_inventory_move,
        inventory_move_sound = item_sounds.combinator_inventory_move,
    },
    {
        type = "item",
        name = "position-beacon",
        icon = "__aai-programmable-vehicles__/graphics/icons/position-beacon.png",
        icon_size = 64,
        flags = {},
        subgroup = structures_subgroup,
        order = "j",
        place_result = "position-beacon",
        stack_size = 100,
        pick_sound = item_sounds.electric_small_inventory_pickup,
        drop_sound = item_sounds.electric_small_inventory_move,
        inventory_move_sound = item_sounds.electric_small_inventory_move,
    },
    {
        type = "item",
        name = "vehicle-deployer",
        icon = "__aai-programmable-vehicles__/graphics/icons/vehicle-deployer.png",
        icon_size = 64,
        flags = {},
        subgroup = structures_subgroup,
        order = "k",
        place_result = "vehicle-deployer",
        stack_size = 10,
        pick_sound = item_sounds.mechanical_large_inventory_pickup,
        drop_sound = item_sounds.mechanical_large_inventory_move,
        inventory_move_sound = item_sounds.mechanical_large_inventory_move,
    },
    {
        type = "item",
        name = "vehicle-depot",
        icon = "__aai-programmable-vehicles__/graphics/icons/vehicle-depot.png",
        icon_size = 64,
        flags = {},
        subgroup = structures_subgroup,
        order = "l",
        place_result = "vehicle-depot",
        stack_size = 10,
        pick_sound = item_sounds.mechanical_large_inventory_pickup,
        drop_sound = item_sounds.mechanical_large_inventory_move,
        inventory_move_sound = item_sounds.mechanical_large_inventory_move,
    },
}

if data.raw["technology"]["programmable-structures"] then
  data:extend{{
    type = "item",
    name = "unit-control",
    icon = "__aai-programmable-structures__/graphics/icon/unit-control.png",
    icon_size = 64,
    flags = {}, -- overwritten to {} in programmable vehicles
    subgroup = structures_subgroup,
    order = "e",
    stack_size = 50,
    place_result = "unit-control",
    pick_sound = item_sounds.metal_large_inventory_pickup,
    drop_sound = item_sounds.metal_large_inventory_move,
    inventory_move_sound = item_sounds.metal_large_inventory_move,
  },
  {
    type = "item",
    name = "unitdata-scan",
    icon = "__aai-programmable-structures__/graphics/icon/unitdata-scan.png",
    icon_size = 64,
    flags = {}, -- overwritten to {} in programmable vehicles
    subgroup = structures_subgroup,
    order = "f",
    stack_size = 50,
    place_result = "unitdata-scan",
    pick_sound = item_sounds.metal_large_inventory_pickup,
    drop_sound = item_sounds.metal_large_inventory_move,
    inventory_move_sound = item_sounds.metal_large_inventory_move,
  },
  {
    type = "item",
    name = "unitdata-control",
    icon = "__aai-programmable-structures__/graphics/icon/unitdata-control.png",
    icon_size = 64,
    flags = {}, -- overwritten to {} in programmable vehicles
    subgroup = structures_subgroup,
    order = "g",
    stack_size = 50,
    place_result = "unitdata-control",
    pick_sound = item_sounds.metal_large_inventory_pickup,
    drop_sound = item_sounds.metal_large_inventory_move,
    inventory_move_sound = item_sounds.metal_large_inventory_move,
  },
  {
    type = "item",
    name = "path-scan",
    icon = "__aai-programmable-structures__/graphics/icon/path-scan.png",
    icon_size = 64,
    flags = {}, -- overwritten to {} in programmable vehicles
    subgroup = structures_subgroup,
    order = "h",
    stack_size = 50,
    place_result = "path-scan",
    pick_sound = item_sounds.metal_large_inventory_pickup,
    drop_sound = item_sounds.metal_large_inventory_move,
    inventory_move_sound = item_sounds.metal_large_inventory_move,
  },
  {
    type = "item",
    name = "path-control",
    icon = "__aai-programmable-structures__/graphics/icon/path-control.png",
    icon_size = 64,
    flags = {}, -- overwritten to {} in programmable vehicles
    subgroup = structures_subgroup,
    order = "i",
    stack_size = 50,
    place_result = "path-control",
    pick_sound = item_sounds.metal_large_inventory_pickup,
    drop_sound = item_sounds.metal_large_inventory_move,
    inventory_move_sound = item_sounds.metal_large_inventory_move,
}}
end
