require("Scripts.Planet.Planet")
require("Scripts.Planet.Resources")
require("Scripts.Planet.Decoratives")
require("Scripts.Planet.Tiles")
require("Scripts.Planet.Noise")
require("Scripts.Planet.MagicField")

require("Scripts.Entity.ScienceMachine")
require("Scripts.Entity.GlassSpaceRocket")
require("Scripts.Entity.CopperPlateMachine")
require("Scripts.Entity.MagicFluidPumper")
require("Scripts.Entity.DiagonalInserter")

require("Scripts.Items.NewSciencePack")
require("Scripts.Items.ConductiveBrick")
require("Scripts.Items.Glass")
require("Scripts.Items.MagicTeseract")
require("Scripts.Items.MagicParts")
require("Scripts.Items.StrongBarrel")
require("Scripts.Items.Cermet")

require("Scripts.Recipes.VariantSciencePacks")
require("Scripts.Recipes.StuffOutOfThinAir")
require("Scripts.Recipes.VariantCopper")
require("Scripts.Recipes.MagicFluidProcessing")
require("Scripts.Recipes.EnrichingMagicParts")
require("Scripts.Recipes.MagicTeseract")

require("Scripts.Fluids.MagicFluid")


require("Scripts.Other.Technologies")
require("Scripts.Other.Groups")
require("Scripts.Other.SpidertronSteal")
require("Scripts.Other.BaseIntegration")
