-- Generated by spritter v1.2.0 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 2, 0 },
  ["file_count"] = 1,
  ["height"] = 122,
  ["line_length"] = 6,
  ["lines_per_file"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {x = 4 / 64, y = -90 / 64},
  ["sprite_count"] = 36,
  ["width"] = 122,
}
